name: Run the unit test suite
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Build and test the commit before build the docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.18'
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: Run the test suite
        run: |
          make test